acadjimia/urls.py
# coding=utf-8

"""acadjimia URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from django.views.generic import TemplateView

from core.views import IndexView, login_or_redirect, RegisterUser, ContactView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^sobre/$', TemplateView.as_view(template_name='aboutus.html'), name='aboutus'),
    url(r'^contato/$', ContactView.as_view(), name='contact'),
    url(r'^entrar/$', login_or_redirect, {'template_name': 'login.html'}, name="login"),
    url(r'^sair/$', logout, {'next_page': 'index'}, name='logout'),
    url(r'^criar-conta/$', RegisterUser.as_view(), name='register'),
    url(r'^catalogo/', include('catalog.urls', namespace='catalog')),
    url(r'^admin/', admin.site.urls),
]

catalog/urls.py
# coding=utf-8

from django.conf.urls import url
from django.views.generic import DetailView
from .models import Course

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^curso/(?P<slug>[\w_-]+)/$',
        DetailView.as_view(
            model=Course,
            context_object_name='course',
            template_name='catalog/course.html'
        ),
        name='course'
    ),
    url(r'^curso/(?P<slug>[\w_-]+)/inscrever/$', views.enroll, name='enroll'),
    url(
        r'^categoria/(?P<slug>[\w_-]+)/$',
        views.CategoryView.as_view(),
        name='category'
    ),
    url(r'^meus-cursos/$', views.MyCoursesView.as_view(), name='mycourses'),
]

catalog/models.py
# coding=utf-8

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):

    name = models.CharField('Nome', max_length=128)
    slug = models.SlugField('Slug')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ('name',)

class CourseManager(models.Manager):

    def featured(self):
        return self.filter(featured=True)

class Course(models.Model):

    name = models.CharField('Nome', max_length=256)
    slug = models.SlugField('Slug')
    category = models.ForeignKey(Category, verbose_name='Categoria')
    description = models.TextField('Descrição', blank=True)
    start_date = models.DateField('Data de Início', blank=True)
    featured = models.BooleanField('Destaque', default=False, blank=True)
    price = models.DecimalField(
        'Preço', default=0, decimal_places=2, max_digits=8
    )
    objects = CourseManager()
    enrolled = models.ManyToManyField(User)

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ('name',)

    def __str__(self):
        return self.name

core/forms.py
# coding=utf-8

from django import forms

class ContactForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

catalog/views.py
# coding=utf-8

from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView

from .models import Course, Category

# Create your views here.

class IndexView(ListView):

    paginate_by = 3
    context_object_name = 'courses'
    model = Course
    template_name = 'catalog/index.html'

class MyCoursesView(ListView):

    paginate_by = 3
    context_object_name = 'courses'
    model = Course
    template_name = 'catalog/index.html'

    def get_queryset(self):
        """
        This function will filter the courses on which the user is enrolled
        """
        return self.request.user.course_set.all()

    def get_context_data(self, **kwargs):
        """
        This function will add a boolean so the template can know the title
        """
        data = super(MyCoursesView, self).get_context_data(**kwargs)
        data['is_mycourses'] = True
        return data


class CategoryView(IndexView):

    def get_queryset(self):
        """
        This function will filter the courses by category
        """
        category = get_object_or_404(Category, slug=self.kwargs['slug'])
        courses = Course.objects.filter(category=category)
        return courses

    def get_context_data(self, **kwargs):
        """
        This function will add the 'category' variable to context
        """
        data = super(CategoryView, self).get_context_data(**kwargs)
        data['category'] = get_object_or_404(Category, slug=self.kwargs['slug'])
        return data

def enroll(request, slug):
    if request.user.is_authenticated():
        course = get_object_or_404(Course, slug=slug)
        if request.user in course.enrolled.all():
            messages.warning(
                request,
                "Você já está inscrito no curso %s." % (course.name)
            )
        else:
            course.enrolled.add(request.user)
            messages.success(
                request,
                "Você se inscreveu no curso %s com sucesso." % (course.name)
            )
        return redirect('catalog:course', slug=slug)
    else:
        return redirect('catalog:course', slug=slug)

core/views.py
# coding=utf-8

from django.core.urlresolvers import reverse_lazy
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView
from django.views.generic.edit import CreateView
from django.contrib import messages
from django.contrib.auth.views import login
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from catalog.models import Course, Category

from .forms import ContactForm

# Create your views here.

class IndexView(TemplateView):

    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        data = super(IndexView, self).get_context_data(**kwargs)
        data['courses'] = Course.objects.featured()
        return data

def login_or_redirect(request, *args, **kwargs):
    if (request.user.is_authenticated()):
        return redirect('index')
    else:
        login_view = login(request, *args, **kwargs)
        try:
            login_view.context_data['login_form'] = login_view.context_data['form']
        except Exception:
            pass
        return login_view

class RegisterUser(CreateView):

    template_name = 'register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('login')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('index')
        else:
            return super(RegisterUser, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        messages.success(
            self.request,
            "Usuário cadastrado com sucesso."
        )
        return super(RegisterUser, self).form_valid(form)

class ContactView(FormView):

    form_class = ContactForm
    success_url = reverse_lazy('contact')
    template_name = 'contact.html'

    def form_valid(self, form):
        send_mail(
            'Formulário de Contato',
            form.cleaned_data['message'],
            form.cleaned_data['email'],
            ['a@b.com'],
            fail_silently=False
        )
        messages.success(
            self.request,
            "Sua mensagem foi enviada com sucesso! Obrigado por entrar em contato!"
        )
        return super(ContactView, self).form_valid(form)

catalog/templates/catalog/_course.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <a href="{% url 'catalog:course' course.slug %}">
            <img src="http://placehold.it/350x250" alt="" />
        </a>
        <div class="caption">
            <h3>{{ course.name }}</h3>
            <p>Começa em: {{ course.start_date | date }}</p>
            <p>{{ course.description|linebreaks }}</p>
            <p><a href="{% url 'catalog:course' course.slug %}" class="btn btn-default">Detalhes</a></p>
        </div>
    </div>
</div>

catalog/templates/catalog/course.html
{% extends "index.html" %}

{% block title %}Produto | Acadjimia{% endblock %}

{% block content %}
<div class="row row-content">
    <div class="col-xs-12">
        <h1 align=center>{{ course.name }}<span class="badge">R$ {{ course.price }}</span></h1>
    </div>
    <div class="col-sm-4">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/350x250" alt="" />
        </a>
    </div>
    <div class="col-sm-8">
        <p>Começa em: {{ course.start_date | date }}</p>
        <p>{{ course.description|linebreaks }}</p>
        {% if user.is_authenticated %}
            {% if user in course.enrolled.all %}
                <p><a href="{% url 'catalog:enroll' course.slug %}"
                    class="btn btn-success disabled">Inscrito</a></p>
            {% else %}
                <p><a href="{% url 'catalog:enroll' course.slug %}"
                    class="btn btn-success">Inscrever-se</a></p>
            {% endif %}
        {% endif %}
    </div>
</div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends "index.html" %}

{% load pagination %}

{% block title %}Cursos | Acadjimia{% endblock %}

{% block content %}
<div class="row row-content">
    <div class="col-xs-12">
        <h1 align=center>
            {% if category %}
                Categoria: {{ category.name }}
            {% elif is_mycourses %}
                Meus Cursos
            {% else %}
                Todos os Cursos
            {% endif %}
        </h1>
    </div>
    {% for course in courses %}
	   {% include "catalog/_course.html" %}
	{% endfor %}
</div>
{% pagination request paginator page_obj %}
{% endblock %}

core/templates/aboutus.html
{% extends "index.html" %}

{% load widget_tweaks %}

{% block title %}Quem somos | Acadjimia{% endblock %}

{% block content %}
<div class="row row-content">
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3">
        <h1 align=center>Quem somos</h1>
    </div>
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3">
        <p>A Acadjimia é o mais novo site de cursos do estilo MOOC.</p>
    </div>
</div>
{% endblock %}

core/templates/contact.html
{% extends "index.html" %}

{% load widget_tweaks %}

{% block title %}Contato | Acadjimia{% endblock %}

{% block content %}
<div class="row row-content">
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3">
        <h1 align=center>Entre em contato conosco</h1>
    </div>
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3">
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endfor %}
        <form class="form" method="post" action="{% url 'contact' %}">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="sr_only">{{ field.label }}</label>
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-info btn-sm">Enviar</button>
        </form>
    </div>
</div>
{% endblock %}

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load is_active %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head
         content must come *after* these tags -->

    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/bootstrap-theme.min.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "css/bootstrap-social.css" %}" rel="stylesheet">

    <link href="{% static "css/acadjimia.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <title>{% block title %}Acadjimia{% endblock %}</title>
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">Acadjimia</a>
                <!-- <a class="navbar-brand" href="#"><img src="img/logo.png" height=30 width=41></a> -->
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="{% active '^/$' %}"><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home"
                         aria-hidden="true"></span> Início</a></li>
                    <li class="{% active '^/sobre/$' %}"><a href="{% url 'aboutus' %}"><span class="glyphicon glyphicon-info-sign"
                         aria-hidden="true"></span> Sobre</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"
                         role="button" aria-haspopup="true" aria-expanded="false">
                         <span class="glyphicon glyphicon-list-alt"
                         aria-hidden="true"></span> Categorias <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'catalog:index' %}">Todos os Cursos</a></li>
                            <li role="separator" class="divider"></li>
                            {% for category in categories %}
                                <li>
                                    <a href="{% url 'catalog:category' category.slug %}">
                                        {{ category.name }}
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                     </li>
                    <li class="{% active '^/contato/$' %}"><a href="{% url 'contact' %}">
                        <i class="fa fa-envelope-o"></i> Contato</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'catalog:mycourses' %}">
                            <span class="glyphicon glyphicon-education"></span> Meus cursos
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">
                            <span class="glyphicon glyphicon-log-out"></span> Sair
                        </a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{% url 'register' %}">
                            <span class="glyphicon glyphicon-copy"></span> Cadastrar-se
                        </a>
                    </li>
                    <li>
                        <a href="#" id="navBarLoginButton">
                            <span class="glyphicon glyphicon-log-in"></span> Entrar
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <div id="loginModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content -->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Login</h4>
                </div>
                <div class="modal-body">
                    {% include "loginform.html" %}
                </div>
            </div>
        </div>
    </div>

    <header class="jumbotron">

    <!-- Main component for a primary marketing message or call to action -->
        <div class="container">
            <div class="row row-header">
                <div class="col-xs-12">
                    <h1>Acadjimia</h1>
                    <p style="padding:40px;"></p>
                    <p>Encontre cursos diversos e melhore seu currículo! Aprenda
                         coisas novas todo dia :)</p>
                </div>
            </div>
        </div>
    </header>


    <div class="container">
        <!-- Messages -->
        <div class="row row-content message-row">
            <div class="col-xs-12">
                {% for message in messages %}
        		<div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        			{{ message }}
        		</div>
        		{% endfor %}
            </div>
        </div>
        {% block content %}
        <!-- Carousel -->

        <div class="row row-content">
            <div class="col-xs-12">
                <h1 align=center>Cursos em destaque</h1>
            </div>
            <div class="col-xs-12">
                <div id="mycarousel" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#mycarousel" data-slide-to="0" class="active"></li>
                        <li data-target="#mycarousel" data-slide-to="1"></li>
                        <li data-target="#mycarousel" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <!-- item 0 -->
                        {% for course in courses %}
                        <div class="item {% if forloop.counter == 1 %}active{% endif %}">
                            <!-- <img class="img-responsive" src="{% static "img/python.png" %}" alt="Uthappizza"> -->
                            <div class="carousel-caption">
                                <h2>{{ course.name }}  <span class="badge">R$ {{ course.price }}</span></h2>
                                <p>{{ course.description }}</p>
                                <p><a class="btn btn-primary btn-xs"
                                    href="{% url 'catalog:course' course.slug %}">More &raquo;</a></p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <!-- Controls -->
                    <a class="left carousel-control" href="#mycarousel" role="button" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="right carousel-control" href="#mycarousel" role="button" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                    <div class="btn-group" id="carouselButtons">
                        <button class="btn btn-danger btn-xs" id="carousel-pause">
                            <span class="glyphicon glyphicon-pause" aria-hidden="true"></span>
                        </button>
                        <button class="btn btn-danger btn-xs" id="carousel-play">
                            <span class="glyphicon glyphicon-play" aria-hidden="true"></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
    </div>

    <footer class="row-footer">
        <div class="container">
            <div class="row">
                <div class="col-xs-5 col-xs-offset-1 col-sm-2 col-sm-offset-1">
                    <h5>Links</h5>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'index' %}">Início</a></li>
                        <li><a href="{% url 'aboutus' %}">Sobre</a></li>
                        <li><a href="{% url 'catalog:index' %}">Cursos</a></li>
                        <li><a href="{% url 'contact' %}">Contato</a></li>
                    </ul>
                </div>
                <div class="col-xs-6 col-sm-5">
                    <h5>Nosso endereço</h5>
                    <address>
		              123, Avenida Paulista<br>
		              São Paulo, SP<br>
		              Brasil<br>
		              <i class="fa fa-phone"></i>: +55 11 1234 5678<br>
                      <i class="fa fa-fax"></i>: +55 11 1234 5678<br>
                      <i class="fa fa-envelope"></i>:
                      <a href="mailto:confusion@food.net">contato@acadjimia.com</a>
		           </address>
                </div>
                <div class="col-xs-12 col-sm-4">
                    <div class="nav navbar-nav" style="padding: 40px 10px;">
                        <a class="btn btn-social-icon btn-google-plus" href="http://google.com/+"><i class="fa fa-google-plus"></i></a>
                        <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i class="fa fa-facebook"></i></a>
                        <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/"><i class="fa fa-linkedin"></i></a>
                        <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i class="fa fa-twitter"></i></a>
                        <a class="btn btn-social-icon btn-youtube" href="http://youtube.com/"><i class="fa fa-youtube"></i></a>
                        <a class="btn btn-social-icon" href="mailto:"><i class="fa fa-envelope-o"></i></a>
                    </div>
                </div>
                <div class="col-xs-12">
                    <p style="padding:10px;"></p>
                    <p align=center>© Copyright 2016 Acadjimia</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    <script>
        $(document).ready(function(){
            // For the carousel
            $("#mycarousel").carousel( { interval: 2000 } );
            $("#carousel-pause").click(function(){
                $("#mycarousel").carousel('pause');
            });
            $("#carousel-play").click(function(){
                $("#mycarousel").carousel('cycle');
            });

            // Assignment 4, Task 2: reserve table button
            $("#ReserveTableButton").click(function () {
                $("#reserveModal").modal('toggle');
            });

            // Assignment 4, Task 3: navbar login button
            $("#navBarLoginButton").click(function () {
                $("#loginModal").modal('toggle');
            });
        });
    </script>

</body>

</html>

core/templates/login.html
{% extends "index.html" %}

{% block title %}Entrar | Acadjimia{% endblock %}

{% block content %}
<div class="row row-content">
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3">
        <h1 align=center>Entrar</h1>
    </div>
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3">
        {% include "loginform.html" %}
    </div>
</div>
{% endblock %}

core/templates/loginform.html
{% load widget_tweaks %}

{% for error in login_form.non_field_errors %}
<div class="alert alert-danger">
    {{ error }}
</div>
{% endfor %}
<form class="form" role="login" method="post" action="{% url 'login' %}">
    {% csrf_token %}
    {% for field in login_form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
      <label for="{{ field.auto_id }}" class="sr_only">{{ field.label }}</label>
        {% render_field field class='form-control' %}
        {% for error in field.errors %}
        <span class="help-block">{{ error }}</span>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-info btn-sm">Entrar</button>
    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cancelar</button>
</form>

core/templates/pagination.html
<div class="row">
    <div class="col-md-12">
        <nav>
          <ul class="pagination">
              {% for page in paginator.page_range %}
              <li{% if page_obj.number == page %} class="active"{% endif %}><a href="?page={{ page }}{{ getvars }}">{{ page }}</a></li>
              {% endfor %}
          </ul>
        </nav>
    </div>
</div>

core/templates/register.html
{% extends "index.html" %}

{% load widget_tweaks %}

{% block title %}Criar Conta | Acadjimia{% endblock %}

{% block content %}
<div class="row row-content">
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3">
        <h1 align=center>Cadastre-se na Acadjimia</h1>
    </div>
    <div class="col-xs-8 col-xs-offset-2 col-sm-6 col-sm-offset-3">
        {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ error }}
        </div>
        {% endfor %}
        <form class="form" role="register" method="post" action="{% url 'register' %}">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group{% if field.errors %} has-error{% endif %}">
              <label for="{{ field.auto_id }}" class="sr_only">{{ field.label }}</label>
                {% render_field field class='form-control' %}
                {% for error in field.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-info btn-sm">Cadastrar-se</button>
        </form>
    </div>
</div>
{% endblock %}